### ISSUE TITLE
Support for minimizing at start-up

### ISSUE THREAD

**Issue by cloudyafternoon** [yoneoarai/auto-minimize-tab-groups#1]
I'm looking for an extension that collapses any tab groups after startup. It would be great if you could add this. Ideally, the two options (1. minimize after 5 sec and 2. minimize at start-up) could be selectable.

If I have time, I might even contribute.

Thanks for considering!

**Comment by yoneoarai** [comment]
@cloudyafternoon  I'll look into it! Unfortunately I think that would require an interface, which requires a bit more work than what exists already, and my typescript is pretty weak.

**Comment by yoneoarai** [comment]
@cloudyafternoon I've opened a PR for closing the window on startup. You can test it before I upload by checking out this repo. 

Go to Chrome -> Extensions -> Manage Extensions -> Load Unpacked 
- select the repo directory

**Comment by cloudyafternoon** [comment]
Hello @yoneoarai I tried it out and it worked for me. It took a small while after start-up until the tabs were closed, but I think it was because I have a lot of tabs, so there is much activity going on at start-up, so the extension code execution is slightly delayed. From my perspective it would be ready to be merged.
