### ISSUE TITLE
Massive local space costs

### ISSUE THREAD

**Issue by mpaetzold** [yoneoarai/auto-minimize-tab-groups#3]
Found your extension while searching exactly for what it does, so thanks at first.
When it came to installation, I recognized the huge file download that it required. Never seen anything like a that on any extension before. Taking a look at the store (https://chromewebstore.google.com/detail/auto-minimize-tab-groups/imjkoaaioakpbcgllmffjdolddjaohdi), it also states ~200MB. Quite suspicious for an extension of this little functionality. That actually lead me here. Taking a look at the code, the suspicion grew even more.
Then I checked locally and found out, that the folder of this extension contained a heavy node_modules directory and furthermore an extension.zip containing the whole directory once more.

I think there is a lot that's not necessary within the artifact. Maybe you can improve.

**Comment by yoneoarai** [comment]
@mpaetzold thanks for bringing this up! I'll try to figure out whats happening

**Comment by yoneoarai** [comment]
@mpaetzold I've submit the changes to the chrome store. If you'd like, you can build the extension yourself in the meantime.

Using webpack, the build is now only a few bytes
